const API_SERVER = 'http://lima-vc-1.sdsc.optiputer.net/project/scripts'

export const MAP_ENDPOINT = API_SERVER+'/getDashboard.py'
export const CARD_ENDPOINT = API_SERVER+'/GetSiteDescription.py'
export const AUTHEN_ENDPOINT = API_SERVER+'/signIn.py'
export const SET_TIMEZONE_ENDPOINT = API_SERVER+'/setTimezone.py'
export const SEARCH_RESOURCE_ENDPOINT = API_SERVER+'/Search.py'
export const CHECK_RESERVATION_ENDPOINT = API_SERVER+'/CheckForReservation.py'
export const CONFIRM_RESERVATION_ENDPOINT = API_SERVER+'/CreateReservation.py'
export const CHECK_CONNECTION_TYPE_ENDPOINT = API_SERVER+'/checkConnectionType.py'